# Generated by Django 3.2.5 on 2021-08-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjwt',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
