# Generated by Django 3.2.5 on 2021-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_user', '0002_alter_userjwt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjwt',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
