# Generated by Django 3.2.5 on 2021-07-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplevalue',
            name='data_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='examplevalue',
            name='value',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
