# Generated by Django 3.2.5 on 2021-07-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_example', '0002_auto_20210717_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplevalue',
            name='value',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
