# Generated by Django 3.2.5 on 2021-08-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_example', '0004_examplevalue_data_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplevalue',
            name='data_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
